name: Bug Report
description: Create a report to help improving the app
title: "[Bug Report] "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
        Please note that while you may submit reports in German and English,
        _all communication regarding the report will be in English only_
        to encourage open collaboration within the project.
  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      description: |-
        Add steps to reproduce the behavior.
        If your school supports anonymous login, you may also provide the school id for easier debugging.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Result
      description: |-
        Explain what should happen.
        Please add Screenshots of the original Untis Mobile app for comparison if applicable.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Result
      description: |-
        Explain what actually happened.
        Add Screenshots and Logs if applicable.
    validations:
      required: true
  - type: input
    id: android-version
    attributes:
      label: Android Version
      description: System Settings -> About -> Android version (may differ on your device)
      placeholder: ex. Android 11
    validations:
      required: true
  - type: input
    id: app-version
    attributes:
      label: BetterUntis Version
      description: BetterUntis Settings -> About -> App version
      placeholder: ex. 1.0.0 (1)
    validations:
      required: true
  - type: dropdown
    id: install-source
    attributes:
      label: Installation Source
      options:
        - Google Play
        - F-Droid
        - SapuSeven.com
        - GitHub Release
        - Own Build
        - Other
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: |-
        Add additional information that doesn't fit the categories above.
    validations:
      required: false
