name: Feature Request
description: Suggest an idea for this project
title: "[Feature Request] "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
        
        Please note that while you may submit requests in German and English,
        _all communication regarding the request will be in English only_
        to encourage open collaboration within the project.
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does BetterUntis currently have?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution Ideas
      description: Add any ideas you have that may help solve the problem.
    validations:
      required: false
